### ISSUE TITLE
vidtodo

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#11]
Hi Doko,
This request is unrelated to your github, but could you take a look at vidtodo.py and see if you fix it once again? vidtodo.com, vidtodu.com, and vidtodoo.com are all now hidden behind a cloudflare check. For the past while vidtodu.com didn't have this check, while the other two did. Jewbmx rewote vidtodo.py to use vidtodu as the host, and it worked, but now all three are behind cloudflare.

With gorillavid, movpod, and daclips shutdown we need as many good hosters as we can get.

I know it's asking a lot, but you fixed it once before, here's hoping you'll do it again.

Have a good one.

**Comment by doko-desuka** [comment]
Hi @bjgood,
I'm sorry, I don't have time to look into this. I'll post in that issue that you made over at ResolveURL with some tips of what someone else would have to do.
