### ISSUE TITLE
Still not working watchcartoononline

### ISSUE THREAD

**Issue by daniel-ntl** [doko-desuka/doko.repository#12]
Hi doko, the addon watchcartoononline still not working

**Comment by doko-desuka** [comment]
Are you talking about WatchNixtoons2?  
What do you mean with "still not working", how is it failing? What are you trying to do? Describe the situation more.

**Comment by daniel-ntl** [comment]
i update the addons to 46, but still not working if i click the series,
if i open browser to this link https://watchcartoononline.cc/download/754385748
this is the message, 

 After the shutdown of other anime and cartoon sites, we are moving one step forward. Every stream is now crypted with our free streaming app. This is for your own safety! All you need to do is download it and set up an account.


*NEW* Install our free streaming client *NEW*


Installation will only take a few minutes + you are fully anonym with our client! 

if i go to this https://www.wcostream.com/ahiru-no-sora-episode-25-english-subbed
now the movie shows, .....
so your addons go trough what site? the only working for me is wcostream.com

**Comment by doko-desuka** [comment]
The address I use can be seen in the source code:  
https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L30

**Comment by doko-desuka** [comment]
So the matter is if you can watch things through that website. If it doesn't work in their website, then it definitely won't work in the add-on because it pulls the streams from there.

**Comment by daniel-ntl** [comment]
could you please change your code to this website "https://www.wcostream.com/" (this works)
this link "https://www.thewatchcartoononline.tv" (this dont work) got block by my government,
thx doko

**Comment by doko-desuka** [comment]
Oof, that's easy to do because the HTML between the two domains is different. It's not like an address change, they actually give out different data.

We used to use that domain, but we changed to that ".tv" domain because it was being updated earlier than the other domains.  

Version 0.4.0 is the last update to use that wcostream domain that you're after. You can download it and give it a try:  
https://github.com/doko-desuka/plugin.video.watchnixtoons2/raw/0c38ffb267e55761451a4bd1e844bdbba53abbc4/plugin.video.watchnixtoons2-0.4.0.zip

**Comment by doko-desuka** [comment]
Correction:
\* that's **_not_** easy to do (...)

**Comment by daniel-ntl** [comment]
ok thx doko i'll try the 40. version, i'll give you update about this

**Comment by daniel-ntl** [comment]
Just tried the 4.0, still not work, but the wcostream in browser play nicely, so any other version that has wcostream as basesite?

**Comment by doko-desuka** [comment]
> Just tried the 4.0, its working, thx man, the 4.0 is right for me, because the basesite still wcostream, and its the only opens in my country, thx again

Awesome, good luck
