### ISSUE TITLE
plocker

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#2]
Hey doko,
plocker is down, but here's a fix. Change https://www6.putlockertv.to to https://www6.putlockertv.se. Then it provides working links.

Have a good one, doko. You're one of my favorite people. :).

Later, dude.

**Comment by doko-desuka** [comment]
Hi bjgood, thanks a lot for warning me. I had wondered why it stopped giving links...

Would you believe I'm still using Placenta? It's a slightly modified copy, I think it's so simple and fast... good thing the LS scrapers still work with it.
Thanks again bro

**Comment by bjgood** [comment]
Would you believe I'm still using Covenant? I've modified it slightly, as well. I just like it. That was a good github to visit before they had to shut it down.

Nixgate's github was a good one, too.

Have a good day tomorrow, doko. :).

Later...
