### ISSUE TITLE
Can you look this code over?

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#3]
Can you tell me why this bit of code doesn't work?

[Code]
def url_ok(url):
    r = requests.head(url)
    if r.status_code == 200 or r.status_code == 301:
        return True
    else: return False

def HostChcker():
    if url_ok("https://www6.putlockertv.co"):
        url = 'https://www6.putlockertv.co'

    elif url_ok("https://www6.putlockertv.se"):
        url = 'https://www6.putlockertv.se'

    else: url = 'http://localhost/'
    
    return url

class source:
    def __init__(self):
        self.priority = 1
        self.language = ['en']
        self.domains = ['putlocker.se', 'putlockertv.to']
        self.base_link = 'https://www6.putlockertv.se'

        self.ALL_JS_PATTERN = '<script src=\"(/assets/min/public/all.js?.*?)\"'
        self.DEFAULT_ACCEPT = 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'

        self.BASE_URL = HostChcker()
[/Code]

I'm trying to use it so if putlockertv.to is down (it's up again, BTW) then it will use putlockertv.se instead, but it doesn't work. putlockertv.co status code is 000. I'm just using it because I know it doesn't work.

Later...

**Comment by doko-desuka** [comment]
Hi bjgood.  
1\) On github you need to enclose all code with three grave accents to get multiline code highlight, like this:
\`\`\`
code
\`\`\`
(or paste all the code, highlight it and select "Insert Code" in the formatting toolbar, it's way easier)

2\) The environment I use to write my Kodi scripts is this:
- A windows system (desktop or notebook)
- Python's IDLE (a simple IDE that runs code and also has a terminal for you to test snippets and small scripts), it comes with the standard Python installation. You just have to remember that the latest Python is 3+ and Kodi's is 2.7, they have some differences in module names, functions etc.
- Notepad++ for the bulk of script writing. I also use it to keep the kodi log open and on autoupdate so I can catch any errors quickly (every single script I've ever written for Kodi starts with some errors, like syntax I forgot etc. It's an iterative process).
- Desktop Kodi for testing the scripts and add-ons. I modify the installed files directly, so I can test them right away.

3) Just for cleanliness I'd put all code inside the `source` class. Also, the domain doesn't end in ".co", it's ".to", that's probably why the 000 response.  
https://gist.github.com/doko-desuka/70f9edd28a25d40f7fcbccdb6bae0756

**Comment by bjgood** [comment]
Thanks, doko.
Sorry for the trouble. I know this was a bother for you, and I appreciate it. :).

I knew the putlockertv.co was not a valid address and would fail. I was just trying to get it to drop on through to putlockertv.se (which is valid).

I'll try your code in plocker.py here shortly

Have a great day, bud.

Later...

**Comment by doko-desuka** [comment]
Oh lol, got it. You were doing it as a test.  
Sometimes when testing I also comment the original IF expression and just put "if False:" so that it goes to the "else" every time.

It's not a bother, good luck.
