### ISSUE TITLE
streamplay

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#4]
Hi doko,
Nice fix on vidtodo in resolveurl. If you get the time, might I suggest having a look at streamplay in resolveurl. I never get any working links from it even though it shows up a number of times in a scan (just like vidtodo use to be).

Just a suggestion. Don't get too mad at me. ;).

Have a good one.

**Comment by bjgood** [comment]
Thanks, doko.

Have a good one, bud.

**Comment by doko-desuka** [comment]
Hi. I answered your Issue over here (https://github.com/jsergio123/script.module.resolveurl/issues/87), so I'm going to close this. Sorry it's a dead-end.

**Comment by bjgood** [comment]
I closed the issue over at JSergio's.

Thanks, buddy.
