### ISSUE TITLE
WatchNixtoons

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#5]
Hey doko,
Sorry for posting about this but it appears that watchcartoononline.io has made some changes to their website, and as a result, none of the cartoon series (like Garfield and Friends, Adventure Time, Men in Black, etc.) will play at all. Instead, they have a "I'm not a robot" box that pops up at (least on the website). That probably explains why the Nixtoons addon is not working properly. It could be temporary, like a week or two ago.

If you get a chance could you take a look at it?

Thanks, buddy

**Comment by doko-desuka** [comment]
Hi @bjgood, I saw some discussion on the Addons4Kodi subreddit (do you have a reddit account, by the way?)

Watchcartoononline added a Google ReCaptcha to their videos, which is pretty tough to bypass -- it's outside my skillset at the least. Unless someone figures out a way to solve that, it's a dead-end...

**Comment by bjgood** [comment]
Hi doko,
Never mind this post. Nixtoons is working again. Like I said earlier, it did the same thing a week or two ago. I thought it was gone for good this time due to the "I'm not a robot" thing.

Sorry for the trouble, bud

**Comment by bjgood** [comment]
I'd say that watchcartoononline dot io will eventually implement this recaptcha full time. They're probably tweaking the code to their liking. That would explain why it's back up again for a second time.

Later...
