### ISSUE TITLE
Here's a suggestion...

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#7]
Hi doko,
Here's a suggestion. This addon named Toons R Us by dandymedia is now abandoned. It scrapes from https://kimcartoon.io. It's a fairly good site. It has episode titles just like watchcartoononline. It uses cloudflare to enter the site. Dandy already has a cloudflare python script but it's giving errors according to the kodi log. Yeah, I installed it. It's a good deal similar to Watch Cartoon Online.

Here's a link to the addon if you decide to look it over...
https://github.com/kodil/kodil/blob/master/repo/plugin.video.toonsrus_gw/plugin.video.toonsrus_gw-1.0.1.zip?raw=true

Just trying to help.

Later...

**Comment by bjgood** [comment]
Also, dandy installs his repo when you install Toons-R-Us. It's the dandy.py file. You also need to delete the word dandy from the default.py in the first import line at the very end.

This just prevents his repo from being installed.

**Comment by doko-desuka** [comment]
Hi @bjgood,
thanks, I'll take a look.

Something I want to work on is "Watchnixtoons2", I had some good ideas about using the mobile site, plus caching etc. It should make things lighter for the source website.

**Comment by bjgood** [comment]
Hi doko,
I suggested to nixgates to check out the mobile version of WatchCartoonOnline, but, I guess, he wasn't interested. The mobile site has direct link mp4 files for the episodes.

BTW, https://kimcartoon.io also has a sister site https://kimcartoon.to. It doesn't use cloudflare.

Thanks for the reply.
