### ISSUE TITLE
More a question

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#9]
Doko,
Is the latest code that you posted over at Anorov's site better than the one from openscrapers website? They both work. I was wondering which one to use.

Thanks for your time.

**Comment by doko-desuka** [comment]
Hi @bjgood, on some sites (like **kat dot tv**, I think I it was you that mentioned that one by the way, thanks for that reference), the CF challenge uses the simpler method still supported by the cfscraper of OpenScrapers. But some sites like **subscene dot com** started using a slightly more difficult method, which that update handles too (it's backwards compatible). If they add new methods then it'll need other updates as well.

**Comment by doko-desuka** [comment]
I didn't say which one is better though.  
If you only use sites with the old method then you don't have to make any changes.

**Comment by bjgood** [comment]
Thanks, doko. Are you going to continue to support this new code? If so, where will you post it? At Jewbmx's site?

I saw pro-src was a little bit non-supportive of your code, but others were. I found a site that has an addon for kodi for js2py. It's quite recent, BTW. I don't know if that will help you or not.

Thank, again.

**Comment by doko-desuka** [comment]
If they change the challenge in a way that is dynamic (different code on every load), then there won't be any alternatives other than to use a JS interpreter like js2py. But for the moment it's not a requirement.  
I'm not going to be maintaining that, it was just a nice puzzle.
